.github/workflows/build-secure-storage.yaml
Create the reports directory even the tests fails and copy the content properly
=> fix: Create reports directory even the tests fail and copy the content

.github/workflows/build-end-to-end-test.yaml
- change java distribution
- parametrize github path
- comment out debug ls commands
=> Follow up SRE-753

workflow-init/profile/hawk.yml, workflow-init/profile/nab.yml
https://hawkai.atlassian.net/browse/INTEL-948
=> INTEL-948: added reference account mismatch

workflow-init/profile/nab.yml
=> SRE-1056-copy-secrets-from-entity-resolution-to-risky-words-score

workflow-init/profile/hawk.yml, workflow-init/profile/nab.yml
https://hawkai.atlassian.net/browse/INTEL-1314
=> INTEL-1315 new service rule-builder

workflow-init/profile/hawk.yml, workflow-init/profile/nab.yml
intel-1384: github-action to build Expected Customer Value image
=> intel-1384: github-action to build Expected Customer Value image

workflow-init/profile/hawk.yml, workflow-init/profile/nab.yml
intel-1395: github actions to build Expected Customer Value
=> intel-1395: github actions to build Expected Customer Value

.github/workflows/build-python-multi.yaml
As far as i can tell, the main difference between the ai-scores one and a general one is just these 2 sections where we could set the ECR prefix. (also python 3.10)
For simpler review, here is the diff with ai-scores workflow
=> ERS-78 generalized python multi build

workflow-init/profile/hawk.yml
Java 17 upgrade for tenant management
impact:1 * likelihood:1 = risk:1
=> sre-1382/impact:1 * likelihood:1 = risk:1

workflow-init/profile/hawk.yml
currency-conversion
transaction-announced-event-reducer
case-statistics
feature-enrichment
rule-reset-sink
external-enrichment
case-note
regulatory-check
customer-risk-rating-events-sink
customer-risk-rating-decision-engine
audit-trail
notifications
case-archive
=> update profile for some repositories

.github/workflows/build-python-multi.yaml
https://hawkai.atlassian.net/browse/INTEL-2011
=> Git checkout  b intel 2011

.github/workflows/build-java-module.yaml, .github/workflows/build-java-multi.yaml, repository-detect-changes/action.yml, workflow-init/action.yml
=> fix: unit test and style check for core module and update overlays

.github/workflows/build-end-to-end-test.yaml
Reverts hawk-ai-aml/github-actions#281
=> Revert "NFR-953 Remove test dependencies from config file"

.github/workflows/check-pr-exist.yaml
Added reusable PR exist check workflow
https://hawkai.atlassian.net/browse/SRE-2805
=> SRE-2805: Add check-pr-exist Workflow

.github/workflows/build-java.yaml, workflow-init/action.yml
- Add Sonar env vars to the `Run Tests With Sonar` step 
- SONAR_ORGANIZATION
-  SONAR_HOST_URL
- Secrets already exists
=> ci(FRA-1574): add sonar cloud env variables

.github/workflows/build-python-multi.yaml
https://hawkai.atlassian.net/browse/INTEL-2661
=> roman fix ai-scores generate reports

.github/workflows/build-java-multi.yaml
run `:${{ matrix.module }}:sonar` for each module after jacocoTestReport to run Sonar checks for each module separately
=> build(FRA-2209) update build java multi for Sonar (#330)

.github/workflows/build-python-multi.yaml
- Fix boolean vs string check at Sonar Scan Step
- Correct the same mistake in other steps too
- See mistake evaluation screen shot
=> fix(FRA-2229): Fix python multi build workflow sonar scan step

.github/workflows/build-python-multi.yaml
https://hawkai.atlassian.net/browse/IRM-388
=> IRM-388  build python multi flake8 check

.github/workflows/build-python.yaml
make sure pipenv uses the configured python version
=> ERS-1888 set python version

.github/workflows/build-python-poetry-multi.yaml
Updated workflow to use `pytest.ini` for each module in multi-module projects.
=> ERS-2038 update build-python-poetry-multi workflow

.github/workflows/release-action.yaml, build-e2e-test/action.yaml
Updated `actions/upload-artifact` to v4
https://hawkai.atlassian.net/browse/PE-4177
=> PE-4177: Update `actions/upload-artifact` to v4

.github/workflows/build-python-poetry.yaml
parametirze authorize-poetry step
=> Improve build-python-poetry

.github/workflows/build-java-module.yaml, .github/workflows/build-java-multi.yaml, .github/workflows/build-java.yaml, .github/workflows/build-python-multi.yaml, .github/workflows/build-python-poetry-multi.yaml, .github/workflows/build-python-poetry.yaml, .github/workflows/build-python-uv.yaml, .github/workflows/build-python.yaml
- Sonar has been rolled out to every repo
- Enabled Sonar now is the default
=> ci: Enable Sonar by default

.github/workflows/build-end-to-end-test-groups.yaml
=> NFR-4066 slack notifications for -Dgroups E2E tests

.github/workflows/build-end-to-end-test-groups.yaml, .github/workflows/build-end-to-end-test.yaml
E2E_SSO_LOGIN_USER_4_ROLE_FEDERATION_PASSWORD
=> feat(FLOW-3380): add password for new test user

.github/workflows/build-python-poetry-multi.yaml
https://hawkai.atlassian.net/browse/SCR-2423
=> SCR-2423: Add buildRustLibraries to the build-python-poetry-multi workflow

risk-assessment/__tests__/service/metrics/codeChurn.test.ts, risk-assessment/__tests__/service/metrics/cognitiveComplexity.test.ts, risk-assessment/__tests__/service/metrics/halsteadComplexity.test.ts, risk-assessment/__tests__/service/metrics/logChurn.test.ts, risk-assessment/src/service/metrics/codeChurn.ts, risk-assessment/src/service/metrics/cognitiveComplexity.ts, risk-assessment/src/service/metrics/halsteadComplexity.ts, risk-assessment/src/service/metrics/logChurn.ts, risk-assessment/src/service/metricsRegistry.ts
https://hawkai.atlassian.net/browse/DC-2162
=> feat(DC-2162): Introduce automated metrics

.github/workflows/risk-assessment-trigger.yml, .github/workflows/risk-assessment.yml, risk-assessment/__tests__/service/metrics/cognitiveComplexity.test.ts, risk-assessment/__tests__/service/metrics/halsteadComplexity.test.ts, risk-assessment/__tests__/service/scoringService.test.ts, risk-assessment/__tests__/utils/git.test.ts, risk-assessment/config/risk-questions.json, risk-assessment/dist/index.js, risk-assessment/src/service/metrics/cognitiveComplexity.ts, risk-assessment/src/service/metrics/halsteadComplexity.ts, risk-assessment/src/service/scoringService.ts, risk-assessment/src/utils/git.ts, risk-assessment/tsconfig.json
https://hawkai.atlassian.net/browse/DC-2185
=> fix(DC-2185): Calculate weights properly

.github/workflows/build-python-poetry.yaml
Enable different github runners + custom cleanup scripts
=> SCR-2546 configurable builder
